export type Mitarbeiter = {
    firstname: string;
    surname: string;
    jobTitle: string;
    graduation: undefined;
    phone: undefined;
    email: string;
    image: {
        path: string;
        title: string;
        mime: string;
        description: string;
        tags: Array<any>;
        size: number;
        image: boolean;
        video: boolean;
        audio: boolean;
        archive: boolean;
        document: boolean;
        code: boolean;
        colors: Array<string>;
        width: number;
        height: number;
        created: number;
        modified: number;
        _by: string;
        folder: string;
        _id: string;
    };
    _mby: string;
    _by: string;
    _modified: number;
    _created: number;
    _id: string;
    status: string;
    _pid: undefined;
    _o: number;
    order: undefined;
    children: Array<any>;
};
type MitarbeiterFilter = {
    where: {
        firstname?: string;
        surname?: string;
        jobTitle?: string;
        graduation?: undefined;
        phone?: undefined;
        email?: string;
        image?: {
            path?: string;
            title?: string;
            mime?: string;
            description?: string;
            tags?: Array<any>;
            size?: number;
            image?: boolean;
            video?: boolean;
            audio?: boolean;
            archive?: boolean;
            document?: boolean;
            code?: boolean;
            colors?: Array<string>;
            width?: number;
            height?: number;
            created?: number;
            modified?: number;
            _by?: string;
            folder?: string;
            _id?: string;
        };
        _mby?: string;
        _by?: string;
        _modified?: number;
        _created?: number;
        _id?: string;
        status?: string;
        _pid?: undefined;
        _o?: number;
        order?: undefined;
        children?: Array<any>;
    };
};
declare const client: {
    mitarbeiter: {
        getAll: (filter?: MitarbeiterFilter) => Promise<Mitarbeiter[]>;
        get: (id: string) => Promise<Mitarbeiter>;
    };
};
export default client;
